version: '3.8'

services:
  # backend:
  #   build: .
  #   ports:
  #     - "3001:3001"
  #   environment:
  #     - DATABASE_URL=${DATABASE_URL}
  #   depends_on:
  #     - db
  #   command: sh -c "npm run start:dev"

  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=menu_management
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
